# Generated by Django 5.1.5 on 2026-03-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_bonuslog_id_alter_fundlog_id_and_more"),
        ("accounts", "0002_alter_user_email"),
    ]

    operations = []
