# Generated by Django 6.0.1 on 2026-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_balance_user_left_active_user_right_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='left_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='right_active',
        ),
        migrations.AddField(
            model_name='user',
            name='left_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='right_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
