# Generated by Django 6.0.1 on 2026-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_withdrawalrequest_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
