# Generated by Django 6.0.1 on 2026-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_withdrawalrequest_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('posAdmin', 'POS Admin')], default='customer', max_length=20),
        ),
    ]
