# Generated by Django 6.0.1 on 2026-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='placement_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reff_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
