# Generated by Django 5.1.3 on 2026-03-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_20260305_0939"),
        ("accounts", "0004_user_otp_user_otp_expiry"),
    ]

    operations = []
