# Generated by Django 5.1.3 on 2026-03-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_placement_id_alter_user_reff_id"),
        ("accounts", "0005_merge_20260310_0829"),
    ]

    operations = []
