# Generated by Django 6.0.1 on 2026-03-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_placement_id_alter_user_reff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leadership_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='matching_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_reward_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
