# Generated by Django 6.0.1 on 2026-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_leadership_bonus_user_matching_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_offer_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
