# Generated by Django 6.0.1 on 2026-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_total_left_user_total_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
