# Generated by Django 5.1.3 on 2026-03-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20260325_1005"),
        ("accounts", "0008_user_lifetime_offer_points"),
    ]

    operations = []
