# Generated by Django 6.0.1 on 2026-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_paid_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
