# Generated by Django 6.0.1 on 2026-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('inbound', 'Money In'), ('outbound', 'Money Out')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('matching_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rank_reward_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tour_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('leadership_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Global Fund Balance',
            },
        ),
    ]
