# Generated by Django 6.0.1 on 2026-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(default='Sundarban Courier', max_length=100),
        ),
    ]
