# Generated by Django 6.0.1 on 2026-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_city_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
    ]
