# Generated by Django 6.0.1 on 2026-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_profit_orderitem_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
