# Generated by Django 6.0.1 on 2026-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_points_awarded_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
