# Generated by Django 6.0.1 on 2026-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=None, editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
