# Generated by Django 6.0.1 on 2026-02-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_pv',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
