# Generated by Django 6.0.1 on 2026-03-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
