# Generated by Django 5.1.5 on 2026-03-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_cart_id_alter_category_id_alter_product_id"),
        ("products", "0002_product_barcode_image_product_barcode_number"),
    ]

    operations = []
