# Generated by Django 5.1.3 on 2026-03-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
        ("products", "0003_merge_20260305_0939"),
    ]

    operations = []
