# Generated by Django 6.0.1 on 2026-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
    ]
