# Generated by Django 5.1.3 on 2026-03-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_banner"),
        ("products", "0004_merge_20260310_0829"),
    ]

    operations = []
