# Generated by Django 6.0.1 on 2026-04-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_id_alter_category_id_alter_product_id'),
        ('products', '0005_alter_category_options_alter_product_barcode_image_and_more'),
    ]

    operations = [
    ]
