# Generated by Django 6.0.1 on 2026-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_purchase_price_alter_product_point_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point_value',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
