# Generated by Django 6.0.1 on 2026-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
