# Generated by Django 6.0.1 on 2026-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_point_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
