# Generated by Django 6.0.1 on 2026-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_barcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
