# Generated by Django 6.0.1 on 2026-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_barcode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, help_text='ব্যানারে ক্লিক করলে কোথায় যাবে (ঐচ্ছিক)', null=True),
        ),
    ]
